exclude:
  - 'app/views/style_guide/**/*.slim'

linters:
  LineLength:
    max: 250
  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/ArgumentAlignment
      - Layout/BlockAlignment
      - Layout/EmptyLineAfterGuardClause
      - Layout/EndAlignment
      - Layout/FirstArrayElementIndentation
      - Layout/FirstParameterIndentation
      - Layout/HashAlignment
      - Layout/IndentationWidth
      - Layout/InitialIndentation
      - Layout/LineLength
      - Layout/MultilineArrayBraceLayout
      - Layout/MultilineAssignmentLayout
      - Layout/MultilineHashBraceLayout
      - Layout/MultilineMethodCallIndentation
      - Layout/MultilineMethodDefinitionBraceLayout
      - Layout/MultilineOperationIndentation
      - Layout/ParameterAlignment
      - Layout/TrailingEmptyLines
      - Lint/Void # 除外検討したが見送り
      - Metrics/BlockLength # 除外検討したが見送り
      - Metrics/BlockNesting
      - Naming/FileName
      - Style/FrozenStringLiteralComment # 除外検討したが見送り
      - Style/IdenticalConditionalBranches
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilDo
      - Style/WhileUntilModifier
      - Style/HashSyntax
