exclude:
  - 'app/views/style_guide/**/*.slim'

linters:
  LineLength:
    max: 250
  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/ArgumentAlignment
      - Layout/ArrayAlignment
      - Layout/BlockAlignment
      - Layout/ClosingParenthesisIndentation
      - Layout/EmptyLineAfterGuardClause
      - Layout/EndAlignment
      - Layout/FirstArgumentIndentation
      - Layout/FirstArrayElementIndentation
      - Layout/FirstHashElementIndentation
      - Layout/FirstParameterIndentation
      - Layout/HashAlignment
      - Layout/IndentationConsistency
      - Layout/IndentationWidth
      - Layout/InitialIndentation
      - Layout/LineEndStringConcatenationIndentation
      - Layout/LineLength
      - Layout/MultilineArrayBraceLayout
      - Layout/MultilineAssignmentLayout
      - Layout/MultilineHashBraceLayout
      - Layout/MultilineMethodCallBraceLayout
      - Layout/MultilineMethodCallIndentation
      - Layout/MultilineMethodDefinitionBraceLayout
      - Layout/MultilineOperationIndentation
      - Layout/ParameterAlignment
      - Layout/TrailingEmptyLines
      - Layout/TrailingWhitespace
      - Lint/Void
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Naming/FileName
      - Style/FrozenStringLiteralComment
      - Style/IdenticalConditionalBranches
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilDo
      - Style/WhileUntilModifier
      - Style/HashSyntax # 検討の結果、残す。（詳細は issue #7253 参照）
